blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/CybrosysAssistaInc/Cybrosys-Assista/discussions/categories/feature-requests
      about: Share and vote on feature requests for Cybrosys Assista
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=Cybrosys-assista-ltd.cybrosys-assista&ssr=false#review-details
      about: Enjoying Cybrosys Assista? Leave a review here!
